version: '3.8'

networks:
  mage_network:
    driver: bridge 

services:
  mage_orchestration:
    image: mageai/mageai:latest
    command: mage start /workspaces/Birth-Demographics/project
    env_file:
      - .env 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /workspaces/Birth-Demographics/project
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - ./home/src:/workspaces/Birth-Demographics/project

    restart: on-failure
    networks:
      - mage_network

  data_warehouse:
    image: postgres:13
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
    volumes:
      - data-warehouse-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "warehouse"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: on-failure
    networks:
      - mage_network


  # docker-proxy:
  #   image: bobrik/socat
  #   command: "TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
  #   ports:
  #     - "2376:2375"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - airflow_network

  # dbt:
  #   build: .
  #   image: dbt_in_docker_compose
  #   networks:
  #     - airflow_network
  

volumes:
  data-warehouse-volume: